import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/provider";
import Header from "@/components/header";
import { NuqsAdapter } from "nuqs/adapters/next";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HireMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="group">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NuqsAdapter>
            <div className="w-full min-h-full h-full flex flex-col">
              <div className="block group-[:fullscreen]:hidden">
                <Header />
              </div>
              <Toaster
                position="bottom-right"
                reverseOrder={false}
                gutter={8}
                toastOptions={{
                  duration: 4000,
                  style: {
                    backdropFilter: "blur(10px)",
                    WebkitBackdropFilter: "blur(10px)",
                    background: "rgba(255, 255, 255, 0.15)",
                    border: "1px solid rgba(255, 255, 255, 0.25)",
                    borderRadius: "5px",
                    color: "#fff",
                    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.2)",
                    fontSize: "13px",
                    padding: "18px 20px",
                  },
                  success: {
                    style: {
                      background: "rgba(0, 255, 150, 0.15)",
                      border: "1px solid rgba(0, 255, 150, 0.4)",
                      color: "#008000",
                    },
                    iconTheme: {
                      primary: "#008000",
                      secondary: "#fff",
                    },
                  },
                  error: {
                    style: {
                      background: "rgba(255, 0, 80, 0.15)",
                      border: "1px solid rgba(255, 0, 80, 0.4)",
                      color: "#ff0000",
                    },
                    iconTheme: {
                      primary: "#ff4d6d",
                      secondary: "#fff",
                    },
                  },
                }}
              />

              {children}
            </div>
          </NuqsAdapter>
        </Providers>
      </body>
    </html>
  );
}
